// src/components/analytics/ClicksByLink.vue
<template>
  <div class="flex flex-col gap-4">
    <header class="my-2 flex flex-col gap-2">
      <h3>Clicks By Link</h3>
      <p class="text-caption text-muted-foreground">
        Your most visited links & social icons.
      </p>
    </header>

    <Spinner v-if="isLoading" />

    <p
      v-else-if="!links.length && !icons.length"
      class="text-lead my-2 text-center text-muted-foreground"
    >
      No links or social icons available yet.
    </p>

    <ul v-else class="grid grid-cols-1 gap-2 md:grid-cols-3">
      <li v-for="item in mergedItems" :key="item.url" class="card">
        <div class="mb-2 flex flex-row items-center gap-2">
          <Icon
            v-if="item.type === 'icon' && item.icon"
            :name="item.icon"
            size="20"
            class="text-muted-foreground"
          />
          <h5 class="truncate text-muted-foreground">
            {{ item.type === 'link' ? item.title : item.platform }}
          </h5>
          <span class="text-label whitespace-nowrap">
            - {{ item.clicks }} clicks
          </span>
        </div>
        <div class="flex flex-col gap-1">
          <p class="text-label truncate">
            {{ item.url }}
          </p>
          <p class="text-label text-muted-foreground">
            Created at {{ item.formattedDate }}
          </p>
        </div>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { useIconStore } from "~/lib/stores/iconStore"
import { useLinkStore } from "~/lib/stores/linkStore"

const iconStore = useIconStore()
const linkStore = useLinkStore()

const isLoading = computed(() => iconStore.isLoading || linkStore.isLoading)
const icons = computed(() => iconStore.icons)
const links = computed(() => linkStore.links)

onMounted(async () => {
  await Promise.all([iconStore.fetchIcons(), linkStore.fetchLinks()])
})

interface MergedLinkItem {
  type: "link"
  formattedDate: string
  title: string
  url: string
  createdAt?: Date
  updatedAt?: Date
  clicks: number
}

interface MergedIconItem {
  type: "icon"
  formattedDate: string
  platform: string
  icon: string
  url: string
  createdAt?: Date
  updatedAt?: Date
  clicks: number
}

type MergedItem = MergedLinkItem | MergedIconItem

const mergedItems = computed<MergedItem[]>(() => {
  const typedLinks: MergedLinkItem[] = links.value.map(link => ({
    ...link,
    type: "link",
    clicks: link.clicks ?? 0,
    formattedDate: new Date(link.createdAt ?? 0).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    }),
  }))

  const typedIcons: MergedIconItem[] = icons.value.map(icon => ({
    ...icon,
    type: "icon",
    clicks: icon.clicks ?? 0,
    formattedDate: new Date(icon.createdAt ?? 0).toLocaleDateString("en-US", {
      year: "numeric",
      month: "short",
      day: "numeric",
    }),
  }))

  return [...typedLinks, ...typedIcons]
})
</script>

// src/app/(admin)/analytics/clicks-by-link.tsx
import Spinner from "@/src/components/spinner"
import { useGetClicksByLink } from "@/src/hooks/use-queries"
import { formatDate } from "@/src/lib/utils"
import { Icon } from "@iconify/react"

export default function ClicksByLink() {
	const { data: items = [], isLoading: isClicksByLinkLoading } = useGetClicksByLink()

	return (
		<div className="flex flex-col gap-4">
			<header className="my-2 flex flex-col gap-2">
				<h3>Clicks By Link</h3>
				<p className="text-caption text-muted-foreground">Your most visited links & social icons.</p>
			</header>

			{isClicksByLinkLoading ? (
				<Spinner />
			) : !items.length ? (
				<p className="text-lead my-2 text-center text-muted-foreground">No links or social icons available yet.</p>
			) : (
				<ul className="grid grid-cols-1 gap-2 md:grid-cols-3">
					{items.map((item) => (
						<li key={item.url} className="card">
							{item.type === "link" ? (
								<div className="mb-2 flex flex-row items-center gap-2">
									<h5 className="truncate text-muted-foreground">{item.title}</h5>
									<span className="text-label whitespace-nowrap"> - {item.clicks} clicks</span>
								</div>
							) : (
								<div className="mb-2 flex flex-row items-center gap-2">
									{item.icon && <Icon icon={item.icon} width={20} height={20} className="text-muted-foreground" />}
									<h5 className="truncate text-muted-foreground">{item.platform}</h5>
									<span className="text-label whitespace-nowrap"> - {item.clicks} clicks</span>
								</div>
							)}

							<div className="flex flex-col gap-1">
								<p className="text-label text-muted-foreground">{item.url}</p>
								<p className="text-label text-muted-foreground">Created at {formatDate(item.createdAt)}</p>
							</div>
						</li>
					))}
				</ul>
			)}
		</div>
	)
}
