// src/components/profile/LinkDialog.vue
<template>
  <Dialog :is-open="isOpen" title="Add or Edit Link" @update:is-open="emit('close')">
    <form class="flex flex-col gap-4 p-4">
      <div class="form-group">
        <label for="title" class="text-sm font-medium w-12">Title</label>
        <input id="title" v-model="form.title" type="text" class="input flex-1" placeholder="Enter link title" required>
      </div>

      <div class="form-group">
        <label for="url" class="text-sm font-medium w-12">URL</label>
        <input id="url" v-model="form.url" type="url" class="input flex-1" placeholder="https://example.com" required>
      </div>
    </form>

    <template #footer>
      <button class="btn-danger" @click="emit('close')">
        Cancel
      </button>
      <button class="btn-success" @click="handleSave">
        Save
      </button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
const props = defineProps<{
  isOpen: boolean
  selectedLink?: LinkType | null
}>()

const emit = defineEmits<{
  (e: "close"): void
  (e: "save", payload: LinkType): void
}>()

const form = ref<LinkType>({
  title: "",
  url: "",
})

watch(() => props.isOpen, (open) => {
  if (open) {
    if (props.selectedLink) {
      form.value = { ...props.selectedLink }
    }
    else {
      form.value = { title: "", url: "" }
    }
  }
}, { immediate: true })

function handleSave() {
  emit("save", { ...form.value })
  emit("close")
}
</script>

// src/components/profile/LinkDialog.tsx
import { useEffect, useState } from "react"
import Dialog from "../Dialog"

export default function LinkDialog({ isOpen, onClose, selectedLink, onSave }: LinkDialogProps) {
	const [linkTitle, setLinkTitle] = useState("")
	const [linkUrl, setLinkUrl] = useState("")

	// Pre-fill the form if a link is selected for editing
	useEffect(() => {
		if (selectedLink) {
			setLinkTitle(selectedLink.title)
			setLinkUrl(selectedLink.url)
		} else {
			setLinkTitle("")
			setLinkUrl("")
		}
	}, [selectedLink])

	const handleSubmit = () => {
		if (linkTitle && linkUrl) {
			onSave({ title: linkTitle, url: linkUrl })
			onClose()
		}
	}

	return (
		<Dialog isOpen={isOpen} onClose={onClose} title={selectedLink ? "Edit Link" : "Add Link"}>
			<div className="space-y-2">
				<div>
					<label htmlFor="linkTitle" className="block text-sm font-medium">
						Link Title
					</label>
					<input
						id="linkTitle"
						type="text"
						className="input"
						value={linkTitle}
						onChange={(e) => setLinkTitle(e.target.value)}
						placeholder="Enter link title"
					/>
				</div>

				<div>
					<label htmlFor="linkUrl" className="block text-sm font-medium">
						Link URL
					</label>
					<input
						id="linkUrl"
						type="url"
						className="input"
						value={linkUrl}
						onChange={(e) => setLinkUrl(e.target.value)}
						placeholder="Enter link URL"
					/>
				</div>

				<div className="input-group">
					<button onClick={handleSubmit} className="btn">
						{selectedLink ? "Update Link" : "Add Link"}
					</button>
					<button onClick={onClose} className="btn text-muted-foreground">
						Close
					</button>
				</div>
			</div>
		</Dialog>
	)
}
