// src/app/(admin)/profile/link-dialog.tsx
import Dialog from "@/src/components/dialog"
import { linkSchema, LinkSchemaType } from "@/src/lib/schemas"
import { Icon } from "@iconify/react"
import { useEffect, useState } from "react"

export default function LinkDialog({ isOpen, onClose, selectedLink, onSave }: LinkDialogProps) {
	const [linkTitle, setLinkTitle] = useState("")
	const [linkUrl, setLinkUrl] = useState("")
	const [errors, setErrors] = useState<Partial<LinkSchemaType>>({})

	// Clear or pre-fill form depending on dialog state
	useEffect(() => {
		if (isOpen) {
			if (selectedLink) {
				setLinkTitle(selectedLink.title)
				setLinkUrl(selectedLink.url)
			} else {
				setLinkTitle("")
				setLinkUrl("")
			}
			setErrors({})
		}
	}, [isOpen, selectedLink])

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault()

		const validation = linkSchema.safeParse({ title: linkTitle, url: linkUrl })

		if (!validation.success) {
			const fieldErrors = validation.error.format()
			setErrors({
				title: fieldErrors.title?._errors[0],
				url: fieldErrors.url?._errors[0]
			})
			return
		}

		onSave({ title: linkTitle, url: linkUrl })
		onClose()
	}

	return (
		<Dialog isOpen={isOpen} onClose={onClose} title={selectedLink ? "Edit Link" : "Add Link"}>
			<form onSubmit={handleSubmit} className="space-y-4">
				<div className="flex flex-col gap-2">
					<label htmlFor="linkTitle" className="font-semibold">
						Link Title
					</label>
					<input
						id="linkTitle"
						type="text"
						value={linkTitle}
						onChange={(e) => setLinkTitle(e.target.value)}
						placeholder="Enter link title"
						className="card text-caption text-muted-foreground"
					/>
					{errors.title && <p className="text-caption text-danger-foreground">{errors.title}.</p>}
				</div>

				<div className="flex flex-col gap-2">
					<label htmlFor="linkUrl" className="font-semibold">
						Link URL
					</label>
					<input
						id="linkUrl"
						type="url"
						value={linkUrl}
						onChange={(e) => setLinkUrl(e.target.value)}
						placeholder="Enter link URL"
						className="card text-caption text-muted-foreground"
					/>
					{errors.url && <p className="text-caption text-danger-foreground">{errors.url}.</p>}
				</div>

				<div className="input-group">
					<button type="submit" className="btn-secondary">
						<Icon icon="mdi:check-circle" width={20} height={20} />
						{selectedLink ? "Update Link" : "Add Link"}
					</button>
					<button type="button" onClick={onClose} className="btn">
						<Icon icon="mdi:close-circle" width={20} height={20} />
						Close
					</button>
				</div>
			</form>
		</Dialog>
	)
}

// src/components/profile/LinkDialog.vue
<template>
  <Dialog :is-open="isOpen" :title="dialogTitle" @update:is-open="emit('close')">
    <form class="flex flex-col gap-4" @submit.prevent="handleSubmit">
      <div class="input-group">
        <label for="title" class="text-sm font-medium w-12">Title</label>
        <input
          id="title" v-model="form.title"
          type="text" placeholder="Enter link title"
          required
        >
      </div>

      <div class="input-group">
        <label for="url" class="text-sm font-medium w-12">URL</label>
        <input
          id="url" v-model="form.url"
          type="url" placeholder="https://example.com"
          required
        >
      </div>

      <div v-if="hasErrors" class="flex flex-col gap-2 text-center max-w-sm">
        <span v-for="(msg, key) in formErrors" :key="key" class="text-caption text-danger-foreground">
          {{ msg }}
        </span>
      </div>

      <footer class="flex justify-end">
        <button class="btn-primary w-32" type="submit" :disabled="hasErrors">
          Save
        </button>
      </footer>
    </form>
  </Dialog>
</template>

<script setup lang="ts">
import { linkSchema } from "~/lib/schemas"

const props = defineProps<{
  isOpen: boolean
  selectedLink?: LinkType | null
}>()

const emit = defineEmits<{
  (e: "close"): void
  (e: "save", payload: LinkType): void
}>()

const form = ref<LinkType>({
  title: "",
  url: "",
})

const formErrors = ref<{ [key: string]: string }>({})
const hasErrors = computed(() => Object.keys(formErrors.value).length > 0)

const dialogTitle = computed(() =>
  props.selectedLink ? "Edit Link" : "Add Link",
)

watch(() => props.isOpen, (open) => {
  if (open) {
    form.value = props.selectedLink
      ? { ...props.selectedLink }
      : { title: "", url: "" }
    formErrors.value = {}
  }
}, { immediate: true })

function handleSubmit() {
  formErrors.value = {}

  const result = linkSchema.safeParse(form.value)
  if (!result.success) {
    const firstError = result.error.errors[0]
    formErrors.value[firstError.path[0]] = firstError.message

    return
  }

  emit("save", { ...form.value })
  emit("close")
}
</script>
