// src/app/(admin)/profile/share-account.tsx
import QrCodeDialog from "@/src/app/(admin)/profile/qr-code-dialog"
import useUserStore from "@/src/hooks/use-store"
import { Icon } from "@iconify/react"
import Link from "next/link"
import { useEffect, useState } from "react"

function ShareDropdown({ isOpen, onClose }) {
	const { user } = useUserStore()

	const [isQrCodeDialogOpen, setIsQrCodeDialogOpen] = useState(false)

	const handleClickOutside = (e: MouseEvent) => {
		if (!(e.target as HTMLElement).closest(".popover")) onClose()
	}

	const handleCopy = () => {
		const pageUrl = `https://linknest-live.vercel.app/${user?.slug}`
		navigator.clipboard.writeText(pageUrl)
		alert("Link copied to clipboard!")
	}

	const handleShareX = () => {
		const pageUrl = `https://linknest-live.vercel.app/${user?.slug}`
		const tweetText = `🚀 Check out my #LinkNest profile! 🌟\n\n🔗 ${pageUrl}`
		const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(tweetText)}`
		window.open(twitterUrl, "_blank")
	}

	useEffect(() => {
		if (isOpen) {
			document.addEventListener("click", handleClickOutside)
		} else {
			document.removeEventListener("click", handleClickOutside)
		}
		return () => document.removeEventListener("click", handleClickOutside)
	}, [isOpen])

	return (
		<>
			{isOpen && (
				<div className="popover absolute right-0 top-full">
					<div className="flex flex-col items-start gap-2 text-xs font-semibold">
						<button onClick={handleCopy} className="flex flex-row items-center gap-2 rounded-2xl p-2 hover:bg-muted">
							<Icon icon="mdi:clipboard-multiple-outline" width={20} height={20} />
							Copy Link
						</button>
						<button onClick={handleShareX} className="flex flex-row items-center gap-2 rounded-2xl p-2 hover:bg-muted">
							<Icon icon="simple-icons:x" width={20} height={20} />
							Share on X
						</button>
						<button
							onClick={() => setIsQrCodeDialogOpen(true)}
							className="flex flex-row items-center gap-2 rounded-2xl p-2 hover:bg-muted"
						>
							<Icon icon="mdi:qrcode" width={20} height={20} />
							Get QR Code
						</button>
					</div>
				</div>
			)}

			{isQrCodeDialogOpen && (
				<QrCodeDialog isOpen={isQrCodeDialogOpen} onClose={() => setIsQrCodeDialogOpen(false)} slug={user?.slug} />
			)}
		</>
	)
}

export default function ShareBanner() {
	const { user } = useUserStore()

	const [isDropdownOpen, setIsDropdownOpen] = useState(false)

	return (
		<div className="relative mt-2 flex max-w-lg flex-row justify-between gap-2 rounded-2xl border bg-muted p-2">
			<div className="flex w-full flex-col gap-1 overflow-x-hidden">
				<h5 className="text-foreground">Share your Page:</h5>
				<Link
					href={`/${user?.slug}`}
					title={`linknest-live.vercel.app/${user?.slug}`}
					className="text-label truncate hover:underline"
				>
					linknest-live.vercel.app/{user?.slug}
				</Link>
			</div>

			<div className="input-group">
				<button
					onClick={() => setIsDropdownOpen((prev) => !prev)}
					title="See sharing options"
					className="btn-secondary"
				>
					<Icon icon="mdi:share-variant" width={20} height={20} />
					Share Now
				</button>
			</div>

			<ShareDropdown isOpen={isDropdownOpen} onClose={() => setIsDropdownOpen(false)} />
		</div>
	)
}

// src/components/profile/ShareAccount.vue
<template>
  <div class="relative mt-2 flex max-w-lg flex-row justify-between gap-2 rounded-2xl border bg-muted p-2">
    <div class="flex w-full flex-col gap-1 overflow-x-hidden">
      <h5 class="text-foreground">
        Share your Page:
      </h5>
      <NuxtLink :to="`/${user?.slug}`" :title="`linknest-live.vercel.app/${user?.slug}`" class="text-label truncate hover:underline">
        linknest-live.vercel.app/{{ user?.slug }}
      </NuxtLink>
    </div>

    <div ref="dropdownWrapper" class="input-group relative">
      <button title="See sharing options" class="btn-secondary" @click="toggleDropdown">
        <Icon name="mdi:share-variant" size="20" />
        <span>Share Now</span>
      </button>

      <div v-if="isDropdownOpen" class="popover absolute right-0 top-full">
        <div class="flex flex-col items-start gap-2 text-xs font-semibold">
          <button class="flex flex-row items-center gap-2 rounded-2xl p-2 whitespace-nowrap hover:bg-muted" @click="handleCopy">
            <Icon name="mdi:clipboard-multiple-outline" size="20" />
            <span>Copy Link</span>
          </button>

          <button class="flex flex-row items-center gap-2 rounded-2xl p-2 whitespace-nowrap hover:bg-muted" @click="handleShareTwitter">
            <Icon name="simple-icons:x" size="20" />
            <span>Share on X</span>
          </button>

          <button class="flex flex-row items-center gap-2 rounded-2xl p-2 whitespace-nowrap hover:bg-muted" @click="openDialog">
            <Icon name="mdi:qrcode" size="20" />
            <span>Get QR Code</span>
          </button>
        </div>
      </div>
    </div>
  </div>

  <ProfileQrCodeDialog :is-open="isDialogOpen" :slug="user?.slug ?? ''" @close="closeDialog" />
</template>

<script setup lang="ts">
import { useUserStore } from "~/lib/stores/user-store"

const userStore = useUserStore()

const user = computed(() => userStore.user)

const isDialogOpen = ref(false)
const isDropdownOpen = ref(false)
const dropdownWrapper = ref<HTMLElement | null>(null)

function toggleDropdown() {
  isDropdownOpen.value = !isDropdownOpen.value
}

function openDialog() {
  isDialogOpen.value = true
}
function closeDialog() {
  isDialogOpen.value = false
}

function handleClickOutside(e: MouseEvent) {
  if (dropdownWrapper.value && !dropdownWrapper.value.contains(e.target as Node)) {
    if (isDropdownOpen.value)
      isDropdownOpen.value = false
    if (isDialogOpen.value)
      closeDialog()
  }
}

watch(isDialogOpen, (newVal) => {
  if (newVal) {
    document.addEventListener("click", handleClickOutside)
  }
  else {
    document.removeEventListener("click", handleClickOutside)
  }
})

onBeforeUnmount(() => {
  document.removeEventListener("click", handleClickOutside)
})

function handleCopy() {
  const pageUrl = `https://linknest-live.vercel.app/${user.value?.slug}`
  navigator.clipboard.writeText(pageUrl)
  isDropdownOpen.value = false
}

function handleShareTwitter() {
  const pageUrl = `https://linknest-live.vercel.app/${user.value?.slug}`
  const tweetText = `🚀 Check out my #LinkNest profile! 🌟\n\n🔗 ${pageUrl}`
  const twitterUrl = `https://twitter.com/intent/tweet?text=${encodeURIComponent(
    tweetText
  )}`
  window.open(twitterUrl, "_blank")
  isDropdownOpen.value = false
}

watch([isDropdownOpen, isDialogOpen], ([dropdownOpen, dialogOpen]) => {
  if (dropdownOpen || dialogOpen) {
    document.addEventListener("click", handleClickOutside)
  }
  else {
    document.removeEventListener("click", handleClickOutside)
  }
})

onBeforeUnmount(() => {
  document.removeEventListener("click", handleClickOutside)
})
</script>
