// src/components/Carousel.vue
<template>
  <div class="relative flex max-h-[550px] select-none items-center justify-center overflow-hidden">
    <Transition name="carousel-fade" mode="out-in">
      <div v-if="preset" :key="preset.slug" class="relative w-64 rounded-xl p-2 md:w-[300px]" :style="backgroundStyle">
        <div class="rounded-t-xl bg-gradient-to-r from-primary to-secondary p-1">
          <div class="flex flex-row items-center justify-between rounded-t-xl bg-[#111016] p-2">
            <div class="flex flex-row items-center gap-1">
              <div class="size-2 rounded-full bg-red-500" />
              <div class="size-2 rounded-full bg-yellow-500" />
              <div class="size-2 rounded-full bg-green-500" />
            </div>

            <span class="rounded bg-[#3b3b41] text-[#ebe8e8] p-1 font-mono text-xs">
              @{{ preset.slug }}
            </span>
          </div>
        </div>

        <div class="flex flex-col items-center justify-center gap-2 py-6 text-center">
          <img :src="preset.image" :alt="preset.slug" width="80" height="80" :style="profilePictureStyle">

          <p :style="slugStyle">
            @{{ preset.slug }}
          </p>

          <p :style="descriptionStyle">
            {{ preset.description }}
          </p>

          <ul class="my-2 flex flex-row items-center justify-center gap-2">
            <CarouselIcon
              v-for="icon in preset.icons"
              :key="icon.id"
              :icon="icon.icon"
              :preferences="preferences"
            />
          </ul>

          <ul class="flex flex-col items-center space-y-4 overflow-auto">
            <CarouselLink
              v-for="link in preset.links"
              :key="link.id"
              :title="link.title"
              :preferences="preferences"
            />
          </ul>
        </div>
      </div>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { CAROUSEL_PRESETS } from "~/lib/config/carousel-presets"

const currentIndex = ref(0)

function nextCard() {
  currentIndex.value = (currentIndex.value + 1) % CAROUSEL_PRESETS.length
}

let intervalId: number

onMounted(() => {
  intervalId = window.setInterval(nextCard, 5000)
})

onUnmounted(() => {
  if (intervalId !== undefined) {
    clearInterval(intervalId)
  }
})

const preset = computed(() => {
  return CAROUSEL_PRESETS[currentIndex.value]
})

const preferences = computed(() => (preset.value.preferences) as unknown as UserPreferencesType)

const backgroundStyle = computed(() => {
  return preferences.value.backgroundType === "GRADIENT"
    ? {
        background: `linear-gradient(to bottom, ${preferences.value.backgroundGradientStart}, ${preferences.value.backgroundGradientEnd})`,
      }
    : { backgroundColor: preferences.value.backgroundColor }
})

const profilePictureStyle = computed(() => {
  return {
    borderRadius: preferences.value.profilePictureRadius,
  }
})

const slugStyle = computed(() => {
  return {
    color: preferences.value.slugTextColor,
    fontWeight: preferences.value.slugTextWeight,
    fontSize: preferences.value.slugTextSize,
  }
})

const descriptionStyle = computed(() => {
  return {
    color: preferences.value.headerTextColor,
    fontWeight: preferences.value.headerTextWeight,
    fontSize: preferences.value.headerTextSize,
  }
})
</script>

<style scoped>
.carousel-fade-enter-active,
.carousel-fade-leave-active {
  transition:
    transform 0.5s ease,
    opacity 0.5s ease;
}
.carousel-fade-enter-from {
  transform: translateX(100%);
  opacity: 0;
}
.carousel-fade-leave-to {
  transform: translateX(-100%);
  opacity: 0;
}
</style>

// src/app/(root)/carousel.tsx
"use client";

import { carouselPresets } from "@/src/config/carousel-presets";
import { Icon } from "@iconify/react";
import { AnimatePresence, motion } from "framer-motion";
import Image from "next/image";
import { useEffect, useState } from "react";

function CarouselLink({ title, preferences }) {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <li
      className="flex w-full min-w-32 max-w-72 flex-row items-center justify-center text-center"
      style={{
        backgroundColor: isHovered
          ? preferences.linkHoverBackgroundColor
          : preferences.linkBackgroundColor,
        boxShadow: preferences.isLinkShadow
          ? preferences.linkShadowWeight === "none"
            ? "none"
            : preferences.linkShadowWeight === "light"
              ? `0 2px 4px ${preferences.linkShadowColor}`
              : preferences.linkShadowWeight === "medium"
                ? `0 4px 6px ${preferences.linkShadowColor}`
                : `0 6px 10px ${preferences.linkShadowColor}`
          : "none",
        borderRadius: preferences.linkBorderRadius,
        padding: preferences.linkPadding,
        transition: "background-color 0.3s ease, box-shadow 0.3s ease",
      }}
    >
      <span
        onMouseEnter={() => setIsHovered(true)}
        onMouseLeave={() => setIsHovered(false)}
        style={{
          color: preferences.linkTextColor,
          fontWeight: preferences.linkTextWeight,
          fontSize: preferences.linkTextSize,
        }}
      >
        {title}
      </span>
    </li>
  );
}

function CarouselIcon({ icon, preferences }) {
  const [isHovered, setIsHovered] = useState(false);

  return (
    <li
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      className="flex size-10 items-center justify-center rounded-full"
      style={{
        backgroundColor: isHovered
          ? preferences.iconHoverBackgroundColor
          : preferences.iconBackgroundColor,
        boxShadow: preferences.isIconShadow
          ? preferences.iconShadowWeight === "none"
            ? "none"
            : preferences.iconShadowWeight === "light"
              ? `0 2px 4px ${preferences.iconShadowColor}`
              : preferences.iconShadowWeight === "medium"
                ? `0 4px 6px ${preferences.iconShadowColor}`
                : `0 6px 10px ${preferences.iconShadowColor}`
          : "none",
        transition: "background-color 0.3s ease, box-shadow 0.3s ease",
      }}
    >
      <Icon
        icon={icon}
        width={20}
        height={20}
        style={{ color: preferences.iconIconColor }}
      />
    </li>
  );
}

function CarouselCard({ presetId }) {
  const { description, links, image, icons, slug, preferences } =
    carouselPresets[presetId];

  return (
    <div
      className="relative w-64 rounded-xl p-2 opacity-80 md:w-[300px]"
      style={
        preferences.backgroundType === "GRADIENT"
          ? {
              background: `linear-gradient(to bottom, ${preferences.backgroundGradientStart}, ${preferences.backgroundGradientEnd})`,
            }
          : { backgroundColor: preferences.backgroundColor }
      }
    >
      <div className="rounded-t-xl bg-gradient-to-r from-primary to-secondary p-1">
        <div className="flex flex-row items-center justify-between rounded-t-xl bg-[#111016] p-2">
          <div className="flex flex-row items-center gap-1">
            <div className="size-2 rounded-full bg-red-500" />
            <div className="size-2 rounded-full bg-yellow-500" />
            <div className="size-2 rounded-full bg-green-500" />
          </div>
          <div className="rounded bg-[#3b3b41] p-1 font-mono text-xs text-[#c7c4c4]">
            @{slug}
          </div>
        </div>
      </div>

      <div className="flex flex-col items-center justify-center gap-2 py-6 text-center">
        <Image
          src={image}
          alt={slug}
          width={80}
          height={80}
          style={{ borderRadius: preferences.profilePictureRadius }}
        />
        <p
          style={{
            color: preferences.slugTextColor,
            fontWeight: preferences.slugTextWeight,
            fontSize: preferences.slugTextSize,
          }}
        >
          @{slug}
        </p>
        <p
          style={{
            color: preferences.headerTextColor,
            fontWeight: preferences.headerTextWeight,
            fontSize: preferences.headerTextSize,
          }}
        >
          {description}
        </p>
        <ul className="my-2 flex flex-row items-center justify-center gap-2">
          {icons.map((icon) => (
            <CarouselIcon
              key={icon.id}
              icon={icon.icon}
              preferences={preferences}
            />
          ))}
        </ul>
        <ul className="flex flex-col items-center space-y-4 overflow-auto">
          {links.map((link) => (
            <CarouselLink
              key={link.id}
              title={link.title}
              preferences={preferences}
            />
          ))}
        </ul>
      </div>
    </div>
  );
}

export default function Carousel() {
  const [currentIndex, setCurrentIndex] = useState(0);

  const nextCard = () => {
    setCurrentIndex((prevIndex) => (prevIndex + 1) % carouselPresets.length);
  };

  useEffect(() => {
    const intervalId = setInterval(nextCard, 3000);
    return () => clearInterval(intervalId);
  }, []);

  return (
    <div className="relative flex h-[480px] select-none items-center justify-center">
      <AnimatePresence mode="wait">
        <motion.div
          key={currentIndex}
          initial={{ opacity: 0, x: 50 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: -50 }}
          transition={{ duration: 0.4 }}
        >
          <CarouselCard presetId={currentIndex} />
        </motion.div>
      </AnimatePresence>
    </div>
  );
}
