// src/components/footer.tsx
import { Icon } from "@iconify/react"
import Link from "next/link"

export default function Footer() {
	return (
		<footer className="flex flex-col items-center justify-between gap-2 p-8 lg:flex-row">
			<hr className="my-2 w-full" />

			<div className="mx-4 whitespace-nowrap font-light text-muted-foreground">
				<p className="text-caption text-muted-foreground">© 2025 Matheus Mortari. All rights reserved.</p>
			</div>

			<div className="mx-4 flex flex-row gap-4 text-muted-foreground">
				<Link href="https://github.com/matimortari" target="_blank" rel="noopener noreferrer">
					<Icon icon="simple-icons:github" width={25} height={25} className="scale-md hover:text-accent" />
				</Link>
				<Link href="https://www.linkedin.com/in/matheus-mortari-19rt" target="_blank" rel="noopener noreferrer">
					<Icon icon="simple-icons:linkedin" width={25} height={25} className="scale-md hover:text-accent" />
				</Link>
			</div>
		</footer>
	)
}

// app/components/footer.vue
<template>
  <footer class="flex flex-col items-center justify-between gap-2 p-8 md:flex-row">
    <p class="text-muted-foreground text-sm whitespace-nowrap">
      © {{ new Date().getFullYear() }} LinkNest. All rights reserved.
    </p>

    <span class="my-2 w-full border-b" />

    <div class="text-muted-foreground mx-4 flex items-center gap-4 text-sm font-light whitespace-nowrap">
      <nuxt-link to="/legal/privacy" class="hover:text-accent underline">
        Privacy Policy
      </nuxt-link>
      <nuxt-link to="/legal/terms" class="hover:text-accent underline">
        Terms of Service
      </nuxt-link>
      <nuxt-link to="https://github.com/matimortari/linknest" target="_blank" rel="noopener noreferrer">
        <icon name="simple-icons:github" size="25" class="hover:scale-md hover:text-accent transition-all" />
      </nuxt-link>
    </div>
  </footer>
</template>
