// src/components/UserLink.tsx
"use client"

import { Icon } from "@iconify/react"
import Link from "next/link"
import { useState } from "react"
import { trackClick } from "../services/analyticsService"

export default function UserLink({ url, title, preferences, linkId, userId }) {
	const [isHovered, setIsHovered] = useState(false)

	const handleCopy = () => {
		navigator.clipboard.writeText(url).then(() => {
			alert("Link copied to clipboard!")
		})
	}

	const handleClick = async () => {
		await trackClick(linkId, "link", userId)
	}

	return (
		<li
			onMouseEnter={() => setIsHovered(true)}
			onMouseLeave={() => setIsHovered(false)}
			className="flex w-full min-w-32 max-w-72 flex-row items-center justify-between px-4 text-center"
			style={{
				backgroundColor: isHovered ? preferences.linkHoverBackgroundColor : preferences.linkBackgroundColor,
				boxShadow: preferences.isLinkShadow
					? preferences.linkShadowWeight === "none"
						? "none"
						: preferences.linkShadowWeight === "light"
						? `0px 1px 2px ${preferences.linkShadowColor}`
						: preferences.linkShadowWeight === "medium"
						? `0 2px 6px ${preferences.linkShadowColor}`
						: `1px 3px 10px ${preferences.linkShadowColor}`
					: "none",
				borderRadius: preferences.linkBorderRadius,
				padding: preferences.linkPadding,
				transition: "background-color 0.3s ease, box-shadow 0.3s ease"
			}}
		>
			<Link href={url} target="_blank" rel="noopener noreferrer" className="flex-grow text-center">
				<button onClick={handleClick}>
					<span
						style={{
							color: preferences.linkTextColor,
							fontWeight: preferences.linkTextWeight,
							fontSize: preferences.linkTextSize
						}}
					>
						{title}
					</span>
				</button>
			</Link>
			{preferences.showCopyButton && (
				<button onClick={handleCopy} className="ml-2 flex-shrink-0">
					<Icon icon="mdi:content-copy" width={15} height={15} style={{ color: preferences.linkTextColor }} />
				</button>
			)}
		</li>
	)
}

// app/components/user-link.vue
<template>
  <li
    class="relative flex w-full min-w-32 max-w-80 flex-row items-center justify-center" :style="linkStyle"
    @mouseenter="isHovered = true" @mouseleave="isHovered = false"
  >
    <a
      :href="url" target="_blank"
      rel="noopener noreferrer" class="flex size-full items-center justify-center"
      @click="$emit('click')"
    >
      <span class="mx-2 inline-block truncate px-4 text-center" :style="linkInnerStyle">{{ title }}</span>
    </a>
    <button
      v-if="preferences?.showCopyButton" class="hover:scale-md absolute right-2 flex-shrink-0 transition-all"
      aria-label="Copy Link" @click.stop="copyToClipboard(props.url)"
    >
      <icon :name="copied ? 'mdi:check' : 'mdi:content-copy'" size="15" :style="{ color: preferences?.linkTextColor }" />
    </button>
  </li>
</template>

<script setup lang="ts">
import { useLinkStore } from "~/lib/stores/link-store"
import { copyToClipboard } from "~/lib/utils"

const props = defineProps<({
  url: string
  title: string
  preferences: UserPreferencesType
})>()

defineEmits(["click"])

const linkStore = useLinkStore()

const isHovered = ref(false)
const copied = ref(false)

const linkStyle = computed(() => {
  return linkStore.getLinkStyle(props.preferences, isHovered.value)
})
const linkInnerStyle = computed(() => {
  return linkStore.getLinkInnerStyle(props.preferences)
})
</script>
