// src/components/Loading.vue
<template>
  <div class="flex min-h-screen flex-col items-center justify-center gap-4">
    <div class="relative h-1 w-1/2 overflow-hidden rounded-full bg-muted">
      <div class="absolute h-full w-1/2 animate-bar bg-gradient-to-r from-primary to-secondary rounded-full" />
    </div>
    <p class="text-caption text-muted-foreground">
      Loading<span class="dot one">.</span><span class="dot two">.</span><span class="dot three">.</span>
    </p>
  </div>
</template>

<style scoped>
.dot {
  opacity: 0;
  animation: fadeIn 1.2s infinite;
}
.dot.one {
  animation-delay: 0s;
}
.dot.two {
  animation-delay: 0.2s;
}
.dot.three {
  animation-delay: 0.4s;
}

@keyframes fadeIn {
  0%,
  100% {
    opacity: 0;
  }
  50% {
    opacity: 1;
  }
}

@keyframes slideBar {
  0% {
    left: -50%;
  }
  100% {
    left: 100%;
  }
}

.animate-bar {
  animation: slideBar 2s linear infinite;
  position: absolute;
  top: 0;
  left: -50%;
}
</style>

// src/app/(admin)/loading.tsx
"use client";

import { motion } from "framer-motion";

export default function Loading() {
  return (
    <div className="flex min-h-screen w-full flex-col items-center justify-center gap-4">
      <motion.div
        initial={{ width: 0 }}
        animate={{ width: "10%" }}
        transition={{
          repeat: Infinity,
          duration: 2,
          ease: "linear",
        }}
        className="h-1 w-1/2 rounded-full bg-gradient-to-r from-primary to-secondary"
      />

      <motion.p
        animate={{ opacity: [0.3, 1, 0.3] }}
        transition={{ duration: 1.4, repeat: Infinity, ease: "linear" }}
        className="text-caption text-muted-foreground"
      >
        Loading
        <motion.span
          animate={{
            opacity: [0, 1, 0],
            transition: { duration: 1, repeat: Infinity },
          }}
        >
          .
        </motion.span>
        <motion.span
          animate={{
            opacity: [0, 1, 0],
            transition: { duration: 1, repeat: Infinity, delay: 0.3 },
          }}
        >
          .
        </motion.span>
        <motion.span
          animate={{
            opacity: [0, 1, 0],
            transition: { duration: 1, repeat: Infinity, delay: 0.6 },
          }}
        >
          .
        </motion.span>
      </motion.p>
    </div>
  );
}
