// src/components/preferences/appearance-form.vue
<template>
  <div v-if="preferences">
    <header class="my-2 flex flex-col gap-2">
      <h3>Appearance</h3>
      <p class="text-caption text-muted-foreground">
        Customize the appearance for your page.
      </p>
    </header>

    <div class="navigation-group flex-wrap justify-between border-b py-2">
      <div class="flex flex-row flex-wrap items-center gap-1">
        <button
          v-for="t in tabs" :key="t.value"
          class="btn" :class="{ 'btn-selected': activeTab === t.value }"
          @click="setActiveTab(t.value)"
        >
          {{ t.label }}
        </button>
      </div>

      <div class="flex flex-row items-center gap-1">
        <button class="btn-primary" @click="handleUpdatePreferences">
          <Icon name="mdi:content-save-check" size="20" />
          <span>{{
            status === 'saved'
              ? 'Saved!'
              : status === 'reset'
                ? 'Reset!'
                : 'Save Changes'
          }}</span>
        </button>

        <button title="Reset Preferences" class="btn-danger" @click="handleResetPreferences()">
          <Icon name="mdi:close" size="20" />
        </button>
      </div>
    </div>

    <div v-if="activeTab === 'background'" class="grid grid-cols-1 gap-2 py-2 lg:grid-cols-2">
      <PreferencesRadioOptions
        v-model:value="preferences.backgroundType" name="backgroundType"
        label="Background Type" :options="BACKGROUND_TYPES"
      />
      <div class="flex flex-col gap-2">
        <PreferencesColorInput
          id="backgroundColor" v-model:value="preferences.backgroundColor"
          label="Background Color" :disabled="isBackgroundGradient"
        />
        <PreferencesColorInput
          id="backgroundGradientStart" v-model:value="preferences.backgroundGradientStart"
          label="Gradient Start Color" :disabled="isBackgroundFlat"
        />
        <PreferencesColorInput
          id="backgroundGradientEnd" v-model:value="preferences.backgroundGradientEnd"
          label="Gradient End Color" :disabled="isBackgroundFlat"
        />
      </div>
    </div>

    <div v-if="activeTab === 'user'" class="grid grid-cols-1 gap-2 py-2 lg:grid-cols-2">
      <div class="flex flex-col gap-2">
        <PreferencesSelectInput
          id="supportBanner" v-model:value="preferences.supportBanner"
          label="Support Banner"
          :options="BANNER_OPTIONS"
        />
        <PreferencesSelectInput
          id="profilePictureRadius" v-model:value="preferences.profilePictureRadius"
          label="Profile Picture Radius" :options="RADIUS_SIZES"
        />
        <PreferencesSelectInput
          id="slugTextSize" v-model:value="preferences.slugTextSize"
          label="Username Font Size"
          :options="FONT_SIZES"
        />
        <PreferencesSelectInput
          id="slugTextWeight" v-model:value="preferences.slugTextWeight"
          label="Username Font Weight" :options="FONT_WEIGHTS"
        />
        <PreferencesColorInput
          id="slugTextColor" v-model:value="preferences.slugTextColor"
          label="Username Font Color"
        />
      </div>

      <div class="flex flex-col gap-2">
        <PreferencesSelectInput
          id="headerTextSize" v-model:value="preferences.headerTextSize"
          label="Header Font Size" :options="FONT_SIZES"
        />
        <PreferencesSelectInput
          id="headerTextWeight" v-model:value="preferences.headerTextWeight"
          label="Header Font Weight" :options="FONT_WEIGHTS"
        />
        <PreferencesColorInput
          id="headerTextColor" v-model:value="preferences.headerTextColor"
          label="Header Font Color"
        />
      </div>
    </div>

    <div v-if="activeTab === 'links'" class="grid grid-cols-1 gap-2 py-2 lg:grid-cols-2">
      <div class="flex flex-col gap-2">
        <PreferencesColorInput
          id="linkBackgroundColor" v-model:value="preferences.linkBackgroundColor"
          label="Background Color"
        />
        <PreferencesColorInput id="linkTextColor" v-model:value="preferences.linkTextColor" label="Font Color" />
        <PreferencesSelectInput
          id="linkTextSize" v-model:value="preferences.linkTextSize"
          label="Font Size"
          :options="LINK_FONT_SIZES"
        />
        <PreferencesSelectInput
          id="linkTextWeight" v-model:value="preferences.linkTextWeight"
          label="Font Weight"
          :options="FONT_WEIGHTS"
        />
        <PreferencesSelectInput
          id="linkBorderRadius" v-model:value="preferences.linkBorderRadius"
          label="Radius"
          :options="RADIUS_SIZES"
        />
        <PreferencesSelectInput
          id="linkPadding" v-model:value="preferences.linkPadding"
          label="Padding"
          :options="LINK_PADDING_SIZES"
        />
      </div>

      <div class="flex flex-col gap-2">
        <PreferencesColorInput
          id="linkHoverBackgroundColor" v-model:value="preferences.linkHoverBackgroundColor"
          label="Hover Background Color"
        />
        <PreferencesCheckboxInput id="isLinkShadow" v-model:value="preferences.isLinkShadow" label="Enable Shadow" />
        <PreferencesColorInput
          id="linkShadowColor" v-model:value="preferences.linkShadowColor"
          label="Shadow Color"
          :disabled="isLinkShadowDisabled"
        />
        <PreferencesSelectInput
          id="linkShadowWeight" v-model:value="preferences.linkShadowWeight"
          label="Shadow Weight" :options="SHADOW_WEIGHTS"
          :disabled="isLinkShadowDisabled"
        />
        <PreferencesCheckboxInput
          id="showCopyButton" v-model:value="preferences.showCopyButton"
          label="Show 'Copy to Clipboard' Button"
        />
      </div>
    </div>

    <div v-if="activeTab === 'icons'" class="grid grid-cols-1 gap-2 py-2 lg:grid-cols-2">
      <div class="flex flex-col gap-2">
        <PreferencesColorInput
          id="iconBackgroundColor" v-model:value="preferences.iconBackgroundColor"
          label="Background Color"
        />
        <PreferencesColorInput id="iconIconColor" v-model:value="preferences.iconIconColor" label="Icon Color" />
        <PreferencesColorInput
          id="iconHoverBackgroundColor" v-model:value="preferences.iconHoverBackgroundColor"
          label="Hover Background Color"
        />
      </div>

      <div class="flex flex-col gap-2">
        <PreferencesCheckboxInput id="isIconShadow" v-model:value="preferences.isIconShadow" label="Enable Shadow" />
        <PreferencesColorInput
          id="iconShadowColor" v-model:value="preferences.iconShadowColor"
          label="Shadow Color"
          :disabled="isIconShadowDisabled"
        />
        <PreferencesSelectInput
          id="iconShadowWeight" v-model:value="preferences.iconShadowWeight"
          label="Shadow Weight" :options="SHADOW_WEIGHTS"
          :disabled="isIconShadowDisabled"
        />
      </div>
    </div>

    <div v-if="activeTab === 'themes'">
      <PreferencesThemeForm :set-theme="handleApplyTheme" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { BACKGROUND_TYPES, FONT_SIZES, FONT_WEIGHTS, LINK_FONT_SIZES, LINK_PADDING_SIZES, RADIUS_SIZES, SHADOW_WEIGHTS } from "~/lib/config/appearance-config"
import { BANNER_OPTIONS } from "~/lib/config/banner-config"
import { usePreferencesStore } from "~/lib/stores/preferences-store"

const tabs = [
  { label: "Background", value: "background" },
  { label: "User Info", value: "user" },
  { label: "Links", value: "links" },
  { label: "Social Icons", value: "icons" },
  { label: "Themes", value: "themes" },
]

const preferencesStore = usePreferencesStore()

const activeTab = ref("background")
const status = ref<"idle" | "saved" | "reset">("idle")
const { preferences } = storeToRefs(preferencesStore)

onMounted(async () => {
  if (!preferences.value) {
    await preferencesStore.getPreferences()
  }
})

function setActiveTab(tabValue: string) {
  activeTab.value = tabValue
}

function handleApplyTheme(newPreferences: UserPreferencesType) {
  preferences.value = newPreferences
}

async function handleUpdatePreferences() {
  try {
    await preferencesStore.updatePreferences(preferences.value!)
    status.value = "saved"
  }
  catch (error: any) {
    console.error("Failed to update preferences:", error)
  }
}

async function handleResetPreferences() {
  try {
    await preferencesStore.resetPreferences()
    status.value = "reset"
  }
  catch (error: any) {
    console.error("Failed to reset preferences:", error)
  }
}

watch(status, (newStatus, _, onInvalidate) => {
  if (newStatus !== "idle") {
    const timer = setTimeout(() => {
      status.value = "idle"
    }, 2000)
    onInvalidate(() => clearTimeout(timer))
  }
})

const isBackgroundFlat = computed(() => preferences.value?.backgroundType === "FLAT")
const isBackgroundGradient = computed(() => preferences.value?.backgroundType === "GRADIENT")
const isLinkShadowDisabled = computed(() => !preferences.value?.isLinkShadow)
const isIconShadowDisabled = computed(() => !preferences.value?.isIconShadow)
</script>

// src/app/(admin)/preferences/appearance-form.tsx
import ThemeForm from "@/src/app/(admin)/preferences/theme-form";
import {
  CheckboxInput,
  ColorInput,
  RadioOptions,
  SelectInput,
} from "@/src/components/inputs";
import {
  BACKGROUND_TYPES,
  FONT_SIZES,
  FONT_WEIGHTS,
  LINK_FONT_SIZES,
  LINK_PADDING_SIZES,
  RADIUS_SIZES,
  SHADOW_WEIGHTS,
} from "@/src/config/appearance-config";
import { BANNER_OPTIONS } from "@/src/config/banner-config";
import {
  useResetPreferences,
  useUpdatePreferences,
} from "@/src/hooks/use-mutations";
import { Icon } from "@iconify/react";
import { useEffect, useState } from "react";

export default function AppearanceForm({ preferences, setPreferences }) {
  const { mutate: updatePreferencesMutation, isSuccess: isUpdateSuccess } =
    useUpdatePreferences();
  const { mutate: resetPreferencesMutation, isSuccess: isResetSuccess } =
    useResetPreferences();

  const [activeTab, setActiveTab] = useState("background");
  const [status, setStatus] = useState<"idle" | "saved" | "reset">("idle");
  const [selectedPreferences, setSelectedPreferences] = useState(preferences);

  const handleChange =
    (field: string) =>
    (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
      const value =
        e.target.type === "checkbox" ? e.target.checked : e.target.value;
      setPreferences((prevPreferences: any) => ({
        ...prevPreferences,
        [field]: value,
      }));
    };

  const isBackgroundFlat = selectedPreferences.backgroundType === "FLAT";
  const isBackgroundGradient =
    selectedPreferences.backgroundType === "GRADIENT";
  const isLinkShadowDisabled = !selectedPreferences.isLinkShadow;
  const isIconShadowDisabled = !selectedPreferences.isIconShadow;

  const tabs = [
    { label: "Background", value: "background" },
    { label: "User Info", value: "user" },
    { label: "Links", value: "links" },
    { label: "Social Icons", value: "icons" },
    { label: "Themes", value: "themes" },
  ];

  useEffect(() => {
    if (isUpdateSuccess) setStatus("saved");
    if (isResetSuccess) setStatus("reset");
  }, [isUpdateSuccess, isResetSuccess]);

  useEffect(() => {
    if (status !== "idle") {
      const timer = setTimeout(() => setStatus("idle"), 2000);
      return () => clearTimeout(timer);
    }
  }, [status]);

  useEffect(() => {
    setSelectedPreferences(preferences);
  }, [preferences]);

  return (
    <div>
      <header className="my-2 flex flex-col gap-2">
        <h3>Appearance</h3>
        <p className="text-caption text-muted-foreground">
          Customize the appearance for your page.
        </p>
      </header>

      <div className="flex flex-wrap items-center justify-between gap-4">
        <div className="flex flex-wrap items-center gap-2">
          {tabs.map((t) => (
            <button
              key={t.value}
              className={`btn ${activeTab === t.value ? "btn-selected" : ""}`}
              onClick={() => setActiveTab(t.value)}
            >
              {t.label}
            </button>
          ))}
        </div>
        <div className="input-group justify-end">
          <button
            onClick={() => updatePreferencesMutation(selectedPreferences)}
            className={`btn flex items-center gap-2 transition-all duration-500 ease-in-out ${
              status === "saved" || status === "reset"
                ? "btn-success"
                : "btn-primary"
            }`}
          >
            <Icon icon="mdi:content-save-check" width={20} height={20} />
            {status === "saved"
              ? "Saved!"
              : status === "reset"
                ? "Reset!"
                : "Save Changes"}
          </button>

          <button
            onClick={() => resetPreferencesMutation()}
            title="Reset Preferences"
            className="btn-danger"
          >
            <Icon icon="mdi:close" width={20} height={20} />
          </button>
        </div>
      </div>

      <hr className="my-2" />

      {activeTab === "background" && (
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-2">
          <RadioOptions
            name="backgroundType"
            label="Background Type"
            options={BACKGROUND_TYPES}
            value={selectedPreferences.backgroundType}
            onChange={handleChange("backgroundType")}
          />

          <div className="flex flex-col gap-2">
            <ColorInput
              id="backgroundColor"
              label="Background Color"
              value={selectedPreferences.backgroundColor}
              onChange={handleChange("backgroundColor")}
              disabled={isBackgroundGradient}
            />
            <ColorInput
              id="backgroundGradientStart"
              label="Gradient Start Color"
              value={selectedPreferences.backgroundGradientStart}
              onChange={handleChange("backgroundGradientStart")}
              disabled={isBackgroundFlat}
            />
            <ColorInput
              id="backgroundGradientEnd"
              label="Gradient End Color"
              value={selectedPreferences.backgroundGradientEnd}
              onChange={handleChange("backgroundGradientEnd")}
              disabled={isBackgroundFlat}
            />
          </div>
        </div>
      )}

      {activeTab === "user" && (
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-2">
          <div className="flex flex-col gap-2">
            <SelectInput
              id="supportBanner"
              label="Support Banner"
              options={BANNER_OPTIONS}
              value={selectedPreferences.supportBanner || "NONE"}
              onChange={handleChange("supportBanner")}
            />
            <SelectInput
              id="profilePictureRadius"
              label="Profile Picture Radius"
              options={RADIUS_SIZES}
              value={selectedPreferences.profilePictureRadius}
              onChange={handleChange("profilePictureRadius")}
            />
            <SelectInput
              id="slugTextSize"
              label="Username Font Size"
              options={FONT_SIZES}
              value={selectedPreferences.slugTextSize}
              onChange={handleChange("slugTextSize")}
            />
            <SelectInput
              id="slugTextWeight"
              label="Username Font Weight"
              options={FONT_WEIGHTS}
              value={selectedPreferences.slugTextWeight}
              onChange={handleChange("slugTextWeight")}
            />
            <ColorInput
              id="slugTextColor"
              label="Username Font Color"
              value={selectedPreferences.slugTextColor}
              onChange={handleChange("slugTextColor")}
            />
          </div>

          <div className="flex flex-col gap-2">
            <SelectInput
              id="headerTextSize"
              label="Header Font Size"
              options={FONT_SIZES}
              value={selectedPreferences.headerTextSize}
              onChange={handleChange("headerTextSize")}
            />
            <SelectInput
              id="headerTextWeight"
              label="Header Font Weight"
              options={FONT_WEIGHTS}
              value={selectedPreferences.headerTextWeight}
              onChange={handleChange("headerTextWeight")}
            />
            <ColorInput
              id="headerTextColor"
              label="Header Font Color"
              value={selectedPreferences.headerTextColor}
              onChange={handleChange("headerTextColor")}
            />
          </div>
        </div>
      )}

      {activeTab === "links" && (
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-2">
          <div className="flex flex-col gap-2">
            <ColorInput
              id="linkBackgroundColor"
              label="Background Color"
              value={selectedPreferences.linkBackgroundColor}
              onChange={handleChange("linkBackgroundColor")}
            />
            <ColorInput
              id="linkTextColor"
              label="Font Color"
              value={selectedPreferences.linkTextColor}
              onChange={handleChange("linkTextColor")}
            />
            <SelectInput
              id="linkTextSize"
              label="Font Size"
              options={LINK_FONT_SIZES}
              value={selectedPreferences.linkTextSize}
              onChange={handleChange("linkTextSize")}
            />
            <SelectInput
              id="linkTextWeight"
              label="Font Weight"
              options={FONT_WEIGHTS}
              value={selectedPreferences.linkTextWeight}
              onChange={handleChange("linkTextWeight")}
            />
            <SelectInput
              id="linkBorderRadius"
              label="Radius"
              options={RADIUS_SIZES}
              value={selectedPreferences.linkBorderRadius}
              onChange={handleChange("linkBorderRadius")}
            />
            <SelectInput
              id="linkPadding"
              label="Padding"
              options={LINK_PADDING_SIZES}
              value={selectedPreferences.linkPadding}
              onChange={handleChange("linkPadding")}
            />
          </div>

          <div className="flex flex-col gap-2">
            <ColorInput
              id="linkHoverBackgroundColor"
              label="Hover Background Color"
              value={selectedPreferences.linkHoverBackgroundColor}
              onChange={handleChange("linkHoverBackgroundColor")}
            />
            <CheckboxInput
              id="isLinkShadow"
              label="Enable Shadow"
              checked={selectedPreferences.isLinkShadow}
              onChange={handleChange("isLinkShadow")}
            />
            <ColorInput
              id="linkShadowColor"
              label="Shadow Color"
              value={selectedPreferences.linkShadowColor}
              onChange={handleChange("linkShadowColor")}
              disabled={isLinkShadowDisabled}
            />
            <SelectInput
              id="linkShadowWeight"
              label="Shadow Weight"
              options={SHADOW_WEIGHTS}
              value={selectedPreferences.linkShadowWeight}
              onChange={handleChange("linkShadowWeight")}
              disabled={isLinkShadowDisabled}
            />
            <CheckboxInput
              id="showCopyButton"
              label="Show 'Copy to Clipboard' Button"
              checked={selectedPreferences.showCopyButton}
              onChange={handleChange("showCopyButton")}
            />
          </div>
        </div>
      )}

      {activeTab === "icons" && (
        <div className="grid grid-cols-1 gap-2 lg:grid-cols-2">
          <div className="flex flex-col gap-2">
            <ColorInput
              id="iconBackgroundColor"
              label="Background Color"
              value={selectedPreferences.iconBackgroundColor}
              onChange={handleChange("iconBackgroundColor")}
            />
            <ColorInput
              id="iconIconColor"
              label="Icon Color"
              value={selectedPreferences.iconIconColor}
              onChange={handleChange("iconIconColor")}
            />
            <ColorInput
              id="iconHoverBackgroundColor"
              label="Hover Background Color"
              value={selectedPreferences.iconHoverBackgroundColor}
              onChange={handleChange("iconHoverBackgroundColor")}
            />
          </div>

          <div className="flex flex-col gap-2">
            <CheckboxInput
              id="isIconShadow"
              label="Enable Shadow"
              checked={selectedPreferences.isIconShadow}
              onChange={handleChange("isIconShadow")}
            />
            <ColorInput
              id="iconShadowColor"
              label="Shadow Color"
              value={selectedPreferences.iconShadowColor}
              onChange={handleChange("iconShadowColor")}
              disabled={isIconShadowDisabled}
            />
            <SelectInput
              id="iconShadowWeight"
              label="Shadow Weight"
              options={SHADOW_WEIGHTS}
              value={selectedPreferences.iconShadowWeight}
              onChange={handleChange("iconShadowWeight")}
              disabled={isIconShadowDisabled}
            />
          </div>
        </div>
      )}

      {activeTab === "themes" && <ThemeForm setTheme={setPreferences} />}
    </div>
  );
}
