// app/components/preferences/theme-form.vue
<template>
  <div class="scroll-area grid h-64 grid-cols-1 gap-2 overflow-auto py-2 md:grid-cols-3">
    <button
      v-for="theme in THEMES"
      :key="theme.title"
      :title="theme.title"
      tabindex="0"
      class="flex size-full items-center justify-center rounded-lg border-2 p-8"
      :class="{
        'border-foreground': selectedTheme === theme.title,
        'border-dashed opacity-60': selectedTheme !== theme.title,
      }"
      :style="getThemeButtonStyle(theme.preferences)"
      @click="handleThemeSelection(theme.title)"
    >
      <div class="line-clamp-1 truncate p-2 text-center text-sm" :style="getTitleStyle(theme.preferences)">
        {{ theme.title }}
      </div>
    </button>
  </div>
</template>

<script setup lang="ts">
import { THEMES } from "~/lib/config/themes"

const props = defineProps<{
  setTheme: (preferences: any) => void
}>()

const selectedTheme = ref("")

function handleThemeSelection(title: string) {
  if (THEMES.find(theme => theme.title === title)) {
    selectedTheme.value = title
    props.setTheme(THEMES.find(theme => theme.title === title)?.preferences || {})
  }
}

function getThemeButtonStyle(preferences: any) {
  return {
    backgroundImage:
      preferences.backgroundType === "GRADIENT"
        ? `linear-gradient(to right, ${preferences.backgroundGradientStart}, ${preferences.backgroundGradientEnd})`
        : "none",
    backgroundColor:
      preferences.backgroundType !== "GRADIENT" ? preferences.backgroundColor : "none",
  }
}

function getTitleStyle(preferences: any) {
  const shadowMap = {
    none: "none",
    light: `0px 1px 2px ${preferences.linkShadowColor}`,
    medium: `0 2px 6px ${preferences.linkShadowColor}`,
    heavy: `1px 3px 10px ${preferences.linkShadowColor}`,
  }

  return {
    backgroundColor: preferences.linkBackgroundColor,
    fontWeight: preferences.slugTextWeight,
    color: preferences.linkTextColor,
    borderRadius: preferences.linkBorderRadius,
    boxShadow: preferences.isLinkShadow
      ? shadowMap[(preferences.linkShadowWeight as keyof typeof shadowMap) ?? "none"]
      : "none",
  }
}
</script>

// src/app/(admin)/preferences/theme-form.tsx
import { themes } from "@/src/config/themes";
import { useState } from "react";

export default function ThemeForm({ setTheme }) {
  const [selectedTheme, setSelectedTheme] = useState("");

  const handleThemeSelection = (themeTitle: string) => {
    const selected = themes.find((theme) => theme.title === themeTitle);

    if (selected) {
      setSelectedTheme(themeTitle);
      setTheme(selected.preferences);
    }
  };

  return (
    <div className="preview-scrollbar grid h-64 grid-cols-1 gap-2 overflow-auto lg:grid-cols-3">
      {themes.map(({ title, preferences }) => (
        <button
          key={title}
          onClick={() => handleThemeSelection(title)}
          tabIndex={0}
          title={title}
          className={`flex size-full items-center justify-center rounded-lg border p-8 ${
            selectedTheme === title ? "opacity-40" : "border-muted"
          }`}
          style={{
            backgroundImage:
              preferences.backgroundType === "GRADIENT"
                ? `linear-gradient(to right, ${preferences.backgroundGradientStart}, ${preferences.backgroundGradientEnd})`
                : "none",
            backgroundColor:
              preferences.backgroundType !== "GRADIENT"
                ? preferences.backgroundColor
                : "none",
          }}
        >
          <div
            className="line-clamp-1 truncate p-2 text-center text-sm"
            style={{
              backgroundColor: preferences.linkBackgroundColor,
              fontWeight: preferences.slugTextWeight,
              color: preferences.linkTextColor,
              borderRadius: preferences.linkBorderRadius,
              boxShadow: preferences.isLinkShadow
                ? {
                    none: "none",
                    light: `0px 1px 2px ${preferences.linkShadowColor}`,
                    medium: `0 2px 6px ${preferences.linkShadowColor}`,
                    heavy: `1px 3px 10px ${preferences.linkShadowColor}`,
                  }[preferences.linkShadowWeight ?? "none"]
                : "none",
            }}
          >
            {title}
          </div>
        </button>
      ))}
    </div>
  );
}
