// app/components/profile/qr-code-dialog.vue
<template>
  <Dialog :is-open="isOpen" title="My QR Code" @update:is-open="emit('close')">
    <div class="flex flex-col items-center gap-4">
      <p class="text-sm text-muted-foreground">
        Scan this QR code to visit your profile:
      </p>

      <QrcodeVue :value="props.slug" :size="150" level="M" class="rounded-lg border border-muted bg-white p-2" />

      <button class="hover:underline" @click="() => copyToClipboard(`https://linknest-live.vercel.app/${props.slug}`)">
        @{{ props.slug }}
      </button>
    </div>

    <template #footer>
      <button class="btn-primary w-32" @click="() => copyToClipboard(`https://linknest-live.vercel.app/${props.slug}`)">
        Copy Link
      </button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import QrcodeVue from "qrcode.vue"
import { copyToClipboard } from "~~/app/lib/utils"

const props = defineProps({
  isOpen: Boolean,
  slug: String,
})

const emit = defineEmits(["close", "update:isOpen"])
</script>

// src/app/(admin)/profile/qr-code-dialog.tsx
import Dialog from "@/src/components/dialog";
import { QRCodeCanvas } from "qrcode.react";

export default function QrCodeDialog({ isOpen, onClose, slug }) {
  const handleDownloadQrCode = (slug: string) => {
    const canvas = document.querySelector("canvas");
    if (canvas) {
      const dataUrl = canvas.toDataURL("image/png");
      const link = document.createElement("a");
      link.href = dataUrl;
      link.download = `${slug}-qrcode.png`;
      link.click();
    }
  };

  return (
    <Dialog isOpen={isOpen} onClose={onClose} title="Share QR Code">
      <div className="my-4 flex flex-col items-center gap-4">
        <QRCodeCanvas
          value={`https://linknest-live.vercel.app/${slug}`}
          size={200}
        />

        <p className="text-caption text-muted-foreground">
          Scan this QR code to visit your LinkNest profile!
        </p>

        <div className="input-group">
          <button
            onClick={() => handleDownloadQrCode(slug)}
            title="Download Your QR Code"
            className="btn-secondary"
          >
            Download QR Code
          </button>
          <button onClick={onClose} title="Cancel" className="btn">
            Close
          </button>
        </div>
      </div>
    </Dialog>
  );
}
