// src/components/UserDialog.vue
<template>
  <Dialog :is-open="isOpen" title="Edit Profile Info" @update:is-open="emit('close')">
    <form class="flex flex-col gap-4 p-4">
      <div class="form-group">
        <label for="slug" class="text-sm font-medium w-20">Slug</label>
        <input id="slug" v-model="form.slug" type="text" class="input flex-1" placeholder="Enter your slug" required>
      </div>

      <div class="form-group">
        <label for="description" class="text-sm font-medium w-20">Description</label>
        <input id="description" v-model="form.description" type="text" class="input flex-1" placeholder="Enter your description">
      </div>

      <div class="form-group">
        <label for="image" class="text-sm font-medium w-20">Image URL</label>
        <input id="image" v-model="form.image" type="url" class="input flex-1" placeholder="https://example.com/image.jpg">
      </div>
    </form>

    <template #footer>
      <button class="btn-danger" @click="emit('close')">
        Cancel
      </button>
      <button class="btn-success" @click="handleSave">
        Save
      </button>
    </template>
  </Dialog>
</template>

<script setup lang="ts">
import { useUserStore } from "~/lib/stores/user-store"

const props = defineProps<{
  isOpen: boolean
  slug?: string
  description?: string
  image?: string
}>()

const emit = defineEmits<{
  (e: "close"): void
}>()

const form = ref({
  slug: "",
  description: "",
  image: "",
})

const { user } = storeToRefs(useUserStore())

watch(() => props.isOpen, (open) => {
  if (open) {
    form.value = {
      slug: props.slug || "",
      description: props.description || "",
      image: props.image || "",
    }
  }
  else {
    form.value = { slug: "", description: "", image: "" }
  }
}, { immediate: true })

async function handleSave() {
  try {
    await useUserStore().updateUser({
      ...user.value!,
      slug: form.value.slug,
      description: form.value.description,
      image: form.value.image,
    })

    user.value = { ...form.value }

    emit("close")
  }
  catch (error) {
    console.error("Failed to update user data:", error)
  }
}
</script>

// src/app/(admin)/profile/user-dialog.tsx
import Dialog from "@/src/components/dialog"
import { useUpdateDescription, useUpdateImage, useUpdateSlug } from "@/src/hooks/use-mutations"
import useUserStore from "@/src/hooks/use-store"
import { userSchema, UserSchemaType } from "@/src/lib/schemas"
import { Icon } from "@iconify/react"
import { useEffect, useState } from "react"

export default function UserDialog({ isOpen, onClose }) {
	const { user, updateUser } = useUserStore()

	const { mutate: updateSlug } = useUpdateSlug()
	const { mutate: updateDescription } = useUpdateDescription()
	const { mutate: updateImage } = useUpdateImage()

	const [slug, setSlug] = useState(user?.slug)
	const [description, setDescription] = useState(user?.description)
	const [image, setImage] = useState(user?.image)
	const [errors, setErrors] = useState<Partial<UserSchemaType>>({})

	useEffect(() => {
		if (user) {
			setSlug(user.slug)
			setDescription(user.description)
			setImage(user.image)
			setErrors({})
		}
	}, [user, isOpen])

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault()

		const validation = userSchema.safeParse({ slug, description, image })

		if (!validation.success) {
			const fieldErrors = validation.error.format()
			setErrors({
				slug: fieldErrors.slug?._errors[0],
				description: fieldErrors.description?._errors[0],
				image: fieldErrors.image?._errors[0]
			})
			return
		}

		let userUpdated = false

		if (slug !== user?.slug) {
			updateSlug(slug || "")
			userUpdated = true
		}
		if (description !== user?.description) {
			updateDescription(description || "")
			userUpdated = true
		}
		if (image !== user?.image) {
			updateImage(image || "")
			userUpdated = true
		}

		if (userUpdated) {
			updateUser({
				...user,
				slug,
				description,
				image
			})
		}

		onClose()
	}

	return (
		<Dialog isOpen={isOpen} onClose={onClose} title="Edit User Info">
			<form onSubmit={handleSubmit} className="space-y-4">
				<div className="flex flex-col gap-2">
					<label htmlFor="slug" className="font-semibold">
						Slug
					</label>
					<input
						id="slug"
						type="text"
						value={slug}
						onChange={(e) => setSlug(e.target.value)}
						placeholder="Your unique identifier"
						className="card text-caption text-muted-foreground"
					/>
					{errors.slug && <p className="text-caption text-danger-foreground">{errors.slug}.</p>}
				</div>

				<div className="flex flex-col gap-2">
					<label htmlFor="description" className="font-semibold">
						Description
					</label>
					<input
						id="description"
						type="text"
						value={description}
						onChange={(e) => setDescription(e.target.value)}
						placeholder="A short bio about yourself"
						className="card text-caption text-muted-foreground"
					/>
					{errors.description && <p className="text-caption text-danger-foreground">{errors.description}.</p>}
				</div>

				<div className="flex flex-col gap-2">
					<label htmlFor="image" className="font-semibold">
						Image
					</label>
					<input
						id="image"
						type="url"
						value={image}
						onChange={(e) => setImage(e.target.value)}
						placeholder="Your profile picture URL"
						className="card text-caption text-muted-foreground"
					/>
					{errors.image && <p className="text-caption text-danger-foreground">{errors.image}.</p>}
				</div>

				<div className="input-group">
					<button type="submit" className="btn-secondary">
						<Icon icon="mdi:content-save-check" width={20} height={20} />
						Save Changes
					</button>
					<button type="button" onClick={onClose} className="btn">
						<Icon icon="mdi:close-circle" width={20} height={20} />
						Close
					</button>
				</div>
			</form>
		</Dialog>
	)
}
