// src/components/Spinner.vue
<template>
  <div class="flex size-full items-center justify-center p-12">
    <div
      v-motion class="size-8 rounded-full border-t-2 border-solid border-accent"
      :initial="{ rotate: 0 }" :visible="{
        rotate: 360,
        transition: {
          duration: 800,
          repeat: Infinity,
          ease: 'linear',
        },
      }"
    />
  </div>
</template>

// src/components/Spinner.tsx
import { motion } from "framer-motion"

export default function Spinner() {
	return (
		<div className="flex items-center justify-center p-4">
			<motion.div
				className="size-8 rounded-full border-t-2 border-solid border-accent"
				animate={{ rotate: 360 }}
				transition={{ repeat: Infinity, duration: 0.8, ease: "linear" }}
			/>
		</div>
	)
}
