// src/components/user-link.tsx
"use client"

import { trackClick } from "@/src/services/analytics"
import { Icon } from "@iconify/react"
import Link from "next/link"
import { useState } from "react"

export default function UserLink({ url, title, preferences, linkId, userId }) {
	const [isHovered, setIsHovered] = useState(false)

	const handleCopy = () => {
		navigator.clipboard.writeText(url).then(() => {
			alert("Link copied to clipboard!")
		})
	}

	const handleClick = async () => {
		await trackClick(linkId, "link", userId)
	}

	return (
		<li
			onMouseEnter={() => setIsHovered(true)}
			onMouseLeave={() => setIsHovered(false)}
			className="flex w-full min-w-32 max-w-72 flex-row items-center justify-between px-4 text-center"
			style={{
				backgroundColor: isHovered ? preferences?.linkHoverBackgroundColor : preferences?.linkBackgroundColor,
				boxShadow: preferences?.isLinkShadow
					? preferences?.linkShadowWeight === "none"
						? "none"
						: preferences?.linkShadowWeight === "light"
						? `0px 1px 2px ${preferences?.linkShadowColor}`
						: preferences?.linkShadowWeight === "medium"
						? `0 2px 6px ${preferences?.linkShadowColor}`
						: `1px 3px 10px ${preferences?.linkShadowColor}`
					: "none",
				borderRadius: preferences?.linkBorderRadius,
				padding: preferences?.linkPadding,
				transition: "background-color 0.3s ease, box-shadow 0.3s ease"
			}}
		>
			<Link href={url} target="_blank" rel="noopener noreferrer" className="flex-grow text-center">
				<button onClick={handleClick}>
					<span
						style={{
							color: preferences?.linkTextColor,
							fontWeight: preferences?.linkTextWeight,
							fontSize: preferences?.linkTextSize
						}}
					>
						{title}
					</span>
				</button>
			</Link>
			{preferences?.showCopyButton && (
				<button onClick={handleCopy} className="ml-2 flex-shrink-0">
					<Icon icon="mdi:content-copy" width={15} height={15} style={{ color: preferences?.linkTextColor }} />
				</button>
			)}
		</li>
	)
}

// src/components/UserLink.vue
<template>
  <li
    class="flex w-full min-w-32 max-w-72 flex-row items-center justify-between px-4 text-center"
    :style="linkStyle"
    @mouseenter="isHovered = true"
    @mouseleave="isHovered = false"
  >
    <a :href="url" target="_blank" rel="noopener noreferrer" class="flex-grow text-center" @click="$emit('click')">
      <span :style="linkInnerStyle">
        {{ title }}
      </span>
    </a>

    <button v-if="preferences?.showCopyButton" class="ml-2 flex-shrink-0" @click="handleCopy">
      <Icon name="mdi:content-copy" size="15" :style="{ color: preferences?.linkTextColor }" />
    </button>
  </li>
</template>

<script setup lang="ts">
const props = defineProps<({
  url: string
  title: string
  preferences: UserPreferencesType
})>()

defineEmits(["click"])

const isHovered = ref(false)

const linkStyle = computed(() => {
  const bgColor = isHovered.value
    ? props.preferences?.linkHoverBackgroundColor
    : props.preferences?.linkBackgroundColor

  let boxShadow = "none"
  if (props.preferences?.isLinkShadow) {
    const weight = props.preferences.linkShadowWeight
    const color = props.preferences.linkShadowColor

    boxShadow
      = weight === "none"
        ? "none"
        : weight === "light"
          ? `0px 1px 2px ${color}`
          : weight === "medium"
            ? `0 2px 6px ${color}`
            : `1px 3px 10px ${color}`
  }

  return {
    backgroundColor: bgColor,
    boxShadow,
    borderRadius: props.preferences?.linkBorderRadius,
    padding: props.preferences?.linkPadding,
    transition: "background-color 0.3s ease, box-shadow 0.3s ease",
  }
})

const linkInnerStyle = computed(() => {
  return {
    color: props.preferences?.linkTextColor,
    fontWeight: props.preferences?.linkTextWeight,
    fontSize: props.preferences?.linkTextSize,
  }
})

function handleCopy() {
  navigator.clipboard.writeText(props.url ?? "").then(() => {
  })
}
</script>
