// src/components/profile/UserDialog.tsx
import Dialog from "@/src/components/Dialog"
import { useUpdateDescription, useUpdateImage, useUpdateSlug } from "@/src/hooks/useMutations"
import useUserStore from "@/src/hooks/useUserStore"
import { userSchema, UserSchemaType } from "@/src/lib/formSchema"
import { Icon } from "@iconify/react"
import { useEffect, useState } from "react"

export default function UserDialog({ isOpen, onClose }) {
	const { user, updateUser } = useUserStore()

	const { mutate: updateSlug } = useUpdateSlug()
	const { mutate: updateDescription } = useUpdateDescription()
	const { mutate: updateImage } = useUpdateImage()

	const [slug, setSlug] = useState(user?.slug)
	const [description, setDescription] = useState(user?.description)
	const [image, setImage] = useState(user?.image)
	const [errors, setErrors] = useState<Partial<UserSchemaType>>({})

	useEffect(() => {
		if (user) {
			setSlug(user.slug)
			setDescription(user.description)
			setImage(user.image)
			setErrors({})
		}
	}, [user, isOpen])

	const handleSubmit = (e: React.FormEvent) => {
		e.preventDefault()

		const validation = userSchema.safeParse({ slug, description, image })

		if (!validation.success) {
			const fieldErrors = validation.error.format()
			setErrors({
				slug: fieldErrors.slug?._errors[0],
				description: fieldErrors.description?._errors[0],
				image: fieldErrors.image?._errors[0]
			})
			return
		}

		let userUpdated = false

		if (slug !== user?.slug) {
			updateSlug(slug || "")
			userUpdated = true
		}
		if (description !== user?.description) {
			updateDescription(description || "")
			userUpdated = true
		}
		if (image !== user?.image) {
			updateImage(image || "")
			userUpdated = true
		}

		if (userUpdated) {
			updateUser({
				...user,
				slug,
				description,
				image
			})
		}

		onClose()
	}

	return (
		<Dialog isOpen={isOpen} onClose={onClose} title="Edit User Info">
			<form onSubmit={handleSubmit} className="space-y-4">
				<div className="flex flex-col gap-2">
					<label htmlFor="slug" className="font-semibold">
						Slug
					</label>
					<input
						id="slug"
						type="text"
						value={slug}
						onChange={(e) => setSlug(e.target.value)}
						placeholder="Your unique identifier"
						className="rounded-2xl border p-2 text-sm"
					/>
					{errors.slug && <p className="text-caption text-danger-foreground">{errors.slug}.</p>}
				</div>

				<div className="flex flex-col gap-2">
					<label htmlFor="description" className="font-semibold">
						Description
					</label>
					<input
						id="description"
						type="text"
						value={description}
						onChange={(e) => setDescription(e.target.value)}
						placeholder="A short bio about yourself"
						className="rounded-2xl border p-2 text-sm"
					/>
					{errors.description && <p className="text-caption text-danger-foreground">{errors.description}.</p>}
				</div>

				<div className="flex flex-col gap-2">
					<label htmlFor="image" className="font-semibold">
						Image
					</label>
					<input
						id="image"
						type="url"
						value={image}
						onChange={(e) => setImage(e.target.value)}
						placeholder="Your profile picture URL"
						className="rounded-2xl border p-2 text-sm"
					/>
					{errors.image && <p className="text-caption text-danger-foreground">{errors.image}.</p>}
				</div>

				<div className="input-group">
					<button type="submit" className="btn-secondary">
						<Icon icon="mdi:content-save-check" width={20} height={20} />
						Save Changes
					</button>
					<button type="button" onClick={onClose} className="btn">
						<Icon icon="mdi:close-circle" width={20} height={20} />
						Close
					</button>
				</div>
			</form>
		</Dialog>
	)
}

// src/components/user-dialog.vue
<template>
  <Dialog :is-open="isOpen" title="Edit Profile Info" @update:is-open="emit('close')">
    <form class="flex flex-col gap-4" @submit.prevent="handleSubmit">
      <div class="flex flex-col items-center border-b pb-4">
        <div class="relative size-24">
          <img v-if="form.image" :src="form.image" alt="Profile preview" class="size-full rounded-full border object-cover">
          <input
            id="image"
            type="file"
            accept="image/*"
            class="absolute left-0 top-0 size-full opacity-0"
            @change="handleImageChange"
          >
          <label class="btn absolute -bottom-2 -left-2" for="image">
            <Icon name="ph:upload" size="20" />
          </label>
        </div>
      </div>

      <div class="navigation-group">
        <label for="slug" class="w-20 text-sm font-medium">Slug</label>
        <input
          id="slug" v-model="form.slug"
          type="text" placeholder="Enter your slug"
          required
        >
      </div>

      <div class="navigation-group">
        <label for="description" class="w-20 text-sm font-medium">Description</label>
        <input id="description" v-model="form.description" type="text" placeholder="Enter your description">
      </div>

      <div v-if="hasErrors" class="flex max-w-sm flex-col gap-2 text-center">
        <span v-for="(msg, key) in formErrors" :key="key" class="text-caption text-danger-foreground">{{ msg }} </span>
      </div>

      <footer class="flex justify-end">
        <button class="btn-primary w-32" type="submit" :disabled="hasErrors">
          Save
        </button>
      </footer>
    </form>
  </Dialog>
</template>

<script setup lang="ts">
import { userDataSchema } from "~/lib/schemas"
import { useUserStore } from "~/lib/stores/user-store"

const props = defineProps<{
  isOpen: boolean
  slug?: string
  description?: string
  image?: string
}>()

const emit = defineEmits<{
  (e: "close"): void
}>()

const userStore = useUserStore()

const form = ref({
  slug: "",
  description: "",
  image: "",
})

const formErrors = ref<{ [key: string]: string }>({})

const hasErrors = computed(() => Object.keys(formErrors.value).length > 0)

const { user } = storeToRefs(userStore)

watch(() => props.isOpen, (open) => {
  if (open) {
    form.value = {
      slug: props.slug || "",
      description: props.description || "",
      image: props.image || "",
    }
    formErrors.value = {}
  }
  else {
    form.value = { slug: "", description: "", image: "" }
    formErrors.value = {}
  }
}, { immediate: true })

async function handleImageChange(event: Event) {
  const input = event.target as HTMLInputElement
  if (!input.files || input.files.length === 0)
    return

  const file = input.files[0]
  if (!file)
    return

  const formData = new FormData()
  formData.append("file", file, file.name)
  formData.append("type", "avatar")

  try {
    const response = await userStore.updateUserImage(formData)
    form.value.image = response.imageUrl
    if (user.value) {
      user.value.image = response.imageUrl
    }
  }
  catch (error: any) {
    console.error("Image upload failed:", error)
  }
}

async function handleSubmit() {
  formErrors.value = {}
  const result = userDataSchema.safeParse(form.value)
  if (!result.success) {
    const firstError = result.error.errors[0]
    formErrors.value[firstError.path[0]] = firstError.message

    return
  }
  try {
    await userStore.updateUser({
      ...user.value!,
      ...form.value,
    })
    user.value = { ...form.value }
    emit("close")
  }
  catch (error: any) {
    console.error("Failed to update user data:", error)
  }
}
</script>
