// src/components/profile/LinkList.tsx
import LinkDialog from "@/src/components/profile/LinkDialog"
import Spinner from "@/src/components/Spinner"
import useDialog from "@/src/hooks/useDialog"
import { useAddLink, useDeleteLink, useUpdateLink } from "@/src/hooks/useMutations"
import { useGetLinks } from "@/src/hooks/useQueries"
import { Icon } from "@iconify/react"
import Link from "next/link"
import { useState } from "react"

export default function LinkList() {
	const { isOpen, openDialog, closeDialog } = useDialog()

	const { data: userLinks = [], isLoading: isLinksLoading } = useGetLinks()
	const { mutate: addLink } = useAddLink()
	const { mutate: updateLink } = useUpdateLink()
	const { mutate: deleteLink } = useDeleteLink()

	const [selectedLink, setSelectedLink] = useState<UserLink | null>(null)

	const handleSave = (link: { title: string; url: string }) => {
		if (selectedLink) {
			updateLink({ id: selectedLink.id, ...link })
		} else {
			addLink(link)
		}
		closeDialog()
	}

	return (
		<div className="flex flex-col gap-2">
			<header className="my-2 flex flex-col gap-2">
				<h3>My Links</h3>
				<p className="text-caption text-muted-foreground">Manage your social links.</p>
			</header>

			{isLinksLoading ? (
				<Spinner />
			) : userLinks.length === 0 ? (
				<p className="text-lead my-2 text-center text-muted-foreground">No links here yet. Get started!</p>
			) : (
				<ul className="grid grid-cols-1 gap-2 md:grid-cols-2">
					{userLinks.map((l: UserLink) => (
						<li key={l.id} className="card">
							<div className="flex flex-col gap-2">
								<div className="flex flex-row items-center gap-4">
									<Link href={l.url} target="_blank" rel="noopener noreferrer" className="w-full overflow-hidden">
										<h5 className="truncate">{l.title}</h5>
									</Link>
									<div className="input-group">
										<button
											onClick={() => {
												setSelectedLink(l)
												openDialog()
											}}
											title="Edit Link"
											className="scale-md"
										>
											<Icon icon="mdi:circle-edit-outline" width={20} height={20} className="text-accent" />
										</button>
										<button onClick={() => l.id && deleteLink(l.id)} title="Remove Link" className="scale-md">
											<Icon
												icon="mdi:remove-circle-outline"
												width={20}
												height={20}
												className="text-danger-foreground"
											/>
										</button>
									</div>
								</div>
								<p className="text-label truncate text-muted-foreground">{l.url}</p>
							</div>
						</li>
					))}
				</ul>
			)}

			<div className="input-group justify-end">
				<button
					onClick={() => {
						setSelectedLink(null) // When adding a new link, set selectedLink to null
						openDialog()
					}}
					className="btn-primary"
				>
					<Icon icon="mdi:link-add" width={20} height={20} />
					Add Link
				</button>

				<LinkDialog isOpen={isOpen} onClose={closeDialog} selectedLink={selectedLink} onSave={handleSave} />
			</div>
		</div>
	)
}

// app/components/profile/link-list.vue
<template>
  <div class="section-container flex flex-col gap-2">
    <header class="my-2 flex flex-col gap-2">
      <h3>
        My Links
      </h3>
      <p class="text-caption text-muted-foreground">
        Manage your links.
      </p>
    </header>

    <Spinner v-if="isLoading" />

    <div v-else-if="!links.length" class="text-lead my-2 text-center text-muted-foreground">
      <p>No links yet. Add your first link!</p>
    </div>

    <ul v-else class="grid grid-cols-1 gap-2 md:grid-cols-2">
      <li v-for="link in links" :key="link.id" class="card">
        <div class="flex flex-col gap-2">
          <div class="flex flex-row items-center justify-between">
            <a :href="link.url" target="_blank" rel="noopener" class="max-w-[80%]">
              <h5 class="truncate">
                {{ link.title }}
              </h5>
            </a>

            <div class="flex flex-row items-center gap-1">
              <button @click="handleUpdateLink(link)">
                <Icon name="mdi:circle-edit-outline" size="20" class="hover:scale-md text-accent transition-all" />
              </button>
              <button @click="handleDeleteLink(link.id!)">
                <Icon name="mdi:remove-circle-outline" size="20" class="hover:scale-md text-danger-foreground transition-all" />
              </button>
            </div>
          </div>

          <p class="text-label truncate text-muted-foreground">
            {{ link.url }}
          </p>
        </div>
      </li>
    </ul>

    <div class="navigation-group justify-end">
      <button class="btn-primary" @click="isDialogOpen = true">
        <Icon name="mdi:link-add" size="25" />
        <span>Add Link</span>
      </button>
    </div>
  </div>

  <ProfileLinkDialog :is-open="isDialogOpen" :selected-link="selectedLink" @close="isDialogOpen = false" @save="handleSaveLink" />
</template>

<script setup lang="ts">
import { useLinkStore } from "~/lib/stores/link-store"

const linkStore = useLinkStore()

const { links, isLoading } = storeToRefs(linkStore)
const isDialogOpen = ref(false)
const selectedLink = ref<LinkType | null>(null)

function handleUpdateLink(link: LinkType) {
  try {
    selectedLink.value = link
    isDialogOpen.value = true
  }
  catch (error: any) {
    console.error("Failed to update link:", error)
  }
}

async function handleDeleteLink(id: string) {
  try {
    await linkStore.deleteLink(id)
  }
  catch (error: any) {
    console.error("Failed to delete link:", error)
  }
}

async function handleSaveLink(link: LinkType) {
  try {
    const existingLink = links.value.find(l => l.id === link.id)
    if (existingLink) {
      await linkStore.updateLink({ ...link, id: link.id! })
    }
    else {
      await linkStore.createLink(link)
    }
    isDialogOpen.value = false
  }
  catch (error: any) {
    console.error("Failed to save link:", error)
  }
}

onMounted(async () => {
  if (!links.value.length)
    await linkStore.getLinks()
})
</script>
