// src/components/preferences/DeleteAccount.tsx
import { useDeleteUser } from "@/src/hooks/useMutations"
import { Icon } from "@iconify/react"

export default function DeleteAccount() {
	const { mutate: deleteUser, error } = useDeleteUser()

	const handleDeleteAccount = () => {
		const confirm = window.confirm("Are you sure you want to delete your account?")
		if (!confirm) return false

		deleteUser(undefined, {
			onSuccess: () => {
				window.location.href = "/"
			},
			onError: (err) => {
				alert(error || err.message || "An error occurred while deleting the account.")
			}
		})
	}

	return (
		<div className="flex flex-col gap-4">
			<header className="my-2 flex flex-col gap-2">
				<h3>Delete Account</h3>
				<p className="text-caption text-danger-foreground">This action is irreversible. All data will be lost.</p>
			</header>

			<div className="input-group justify-end md:justify-start">
				<button onClick={handleDeleteAccount} title="Delete Account" className="btn-danger">
					<Icon icon="mdi:user-remove" width={20} height={20} />
					Delete Account
				</button>
			</div>

			{error && <div className="mt-2 text-danger-foreground">{error.message}</div>}
		</div>
	)
}

// src/components/preferences/delete-account.vue
<template>
  <div class="flex flex-col gap-4">
    <header class="my-2 flex flex-col gap-2">
      <h3>Delete Account</h3>
      <p class="text-caption text-danger-foreground">
        This action is irreversible. All data will be lost.
      </p>
    </header>

    <div class="navigation-group justify-end md:justify-start">
      <button title="Delete Account" class="btn-danger" @click="handleDeleteUser">
        <Icon name="mdi:user-remove" size="20" />
        <span>Delete Account</span>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { useUserStore } from "~/lib/stores/user-store"

const userStore = useUserStore()
const { clear } = useUserSession()
const router = useRouter()

async function handleDeleteUser() {
  userStore.error = null
  if (!confirm("Are you sure you want to delete your account?"))
    return

  try {
    await userStore.deleteUser()
    clear()
    await router.push("/")
  }
  catch (error: any) {
    console.error("Failed to delete user:", error)
    userStore.error = error?.message || "Failed to delete account."
  }
}
</script>
